### ISSUE TITLE
Data is not synced with DMP

### ISSUE THREAD

**Issue by BlackSymbol** [Caylis1397/Syncrio#8]
Hello there.
It's probably not a bug, yet Syncrio doesn't seem to work for me and a friend with DMP.

Reproduction:
Setup DMP server and run it for once. Shutdown.
Setup Syncrio server and run it for once. Shutdown.
Update Syncrio config file to use DMP.
Update both config files of DMP and Syncrio to use similar settings (e.g. career mode, same mod control, etc.).
Start DMP server, start Syncrio server.
Start up KSP, enable DMP coop mode on Syncrio.
Add and join both servers (Syncrio first, then DMP).
Create a public group (then friend joins the group).

Now, strange things can happen.
First try: money and contracts were synchronizing correctly. Yet, science wasn't synchronized, so was the tech tree.
Second try (after shutting down both servers and cleaning universe data out of them): I launch the vessel and obtain some money and science (a bit of warp was used). Friend "time sync-s" to me, the money and science is sync-ed to the friend's state (which was not updated once I recovered the vessel), therefore obtained science and money were lost after "time-syncing", yet, the archive in R&D center shows that 2 experiments were performed.

Server: Windows Server 2008 R2.
Client 1: Win 7; KSP 1.3.0.1804
Client 2: Win 10 (if I recall correctly); same KSP version.
Syncrio version (server and client): 0.9.0.1.
DMP version (server and client): 0.2.4.4.
Config files attached.
[Settings_dmp.txt](https://github.com/Caylis1397/Syncrio/files/1290990/Settings_dmp.txt)
[Settings_syncrio.txt](https://github.com/Caylis1397/Syncrio/files/1290991/Settings_syncrio.txt)

Any thoughts?
Thanks in advance

P.s. If that would help, I can enable debug logging level on both servers and then submit the files here.

**Comment by Caylis1397** [comment]
Ok, to start, sorry it took so long to respond. As far as the bug goes, I'm not sure why you lost the data. I would need more info (debug logs) to be able to figure it out, but I do have an idea. Try using the 1.0 Beta 3 version of Syncrio, it's available [here](https://github.com/Caylis1397/Syncrio/tree/master/Release%20Files/Downloads). It might help fix the problem.

**Comment by BlackSymbol** [comment]
Thanks, I will try with the beta later this week and will tell you how it goes.

**Comment by BlackSymbol** [comment]
Well, with beta it's better. Most of the synchronization (science, researched tech-s, money, etc.) is working fine, but the buildings' levels only synchronize after a reconnect to the server (that is, disconnect from DMP, reconnect to Syncrio, reconnect to DMP). I assume it shouldn't work that way, therefore I attach logs if they will help you to track down the issue.

[dmpserver 2017-09-20 02-44-18.txt](https://github.com/Caylis1397/Syncrio/files/1316004/dmpserver.2017-09-20.02-44-18.txt)
[Syncrioserver 2017-09-20 02-44-32.txt](https://github.com/Caylis1397/Syncrio/files/1316005/Syncrioserver.2017-09-20.02-44-32.txt)

Thanks for the help and tell me if I can assist somehow else.

**Comment by Caylis1397** [comment]
Unfortunately, the way the 1.0 beta 3 works, means that you ether have to leave the server, or enter the tracking station to get the building update. I set it up like this so that there was a safety system to keep KSP from crashing when the building updated. For some unknown reason, KSP has all sorts of problems if you try to update certain data while in certain places. For example, trying to update contracts while in the mission building causes KSP's ui to go crazy. Because of problems like the ui breaking, and KSP crashing, I had to set it up so that Syncrio will wait to input the update until you are no longer in a place where the update will break KSP. So buildings don't update when you are in the KSC, tech doesn't update while you are in the RnD, rocket/plane parts don't update while you are in the VAB/SPH, etc. So if the update doesn't get added try changing buildings. Sorry for the long post, and the 3 day wait. I hope this helps.

**Comment by BlackSymbol** [comment]
Thanks for the clarification.
Just few more questions: 
1) What happens if there are two people picking contracts and the contract limit is 2? I guess the server will just use the first 2 contracts that were selected (e.g. clients state will be forced to the server's one once both players have left contract selection)?
2) What happens once contract is completed and flight is reverted? I assume contract will be completed in such a case?

Also a suggestion: it would be nice to have the description on how synchronization works in the readme.md so that mod-users will understand it and it will not confuse them.

P.s. I don't mind the waiting, you're doing great job. Feel free to close the issue.

**Comment by Caylis1397** [comment]
To answer the first question, I had not thought about contract limits when I was making the 1.0 betas. So the server won't account for that, thus allowing more contracts then KSP says you can have.
As for the second question, if you complete a contract all on your own and then revert the contract it will be uncompleted and the reward removed. But if you compete one part of a contract, and another player completes another part (but not the all rest of the contract (e.g., a 3 part contract)) and then you revert, only the part you completed will be undone.
However, because only basic revert support is built at the moment, if the other player completes the rest of the contract (thus completing the whole contract) then the contract will stay completed, but your reward for the part you did will be removed and thus become unobtainable.

So until I complete full revert support, it's best to work on separate contracts, or to minimize use of reverting.

Also, I'll definitely add a better description of the sync system soon. And in the next beta I also plan to add a KSPedia page on how to use Syncrio, and help files for the server.
